name: Client Connect
on:
  push:
    branches: [ client ]

jobs:
  connect:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=idontcare" | jq -r '.value')
          jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< ${TOKEN}
            echo "Signature: $(echo "${TOKEN}" | awk -F'.' '{print $3}')"
