name: Client Connect
on:
  push:
    branches: [ client ]

jobs:
  connect:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Token
        id: oidc
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=idontcare" | jq -r '.value')
          jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< ${TOKEN}
          echo "Signature: $(echo "${TOKEN}" | awk -F'.' '{print $3}')"
          echo "::set-output name=token::${TOKEN}"

      - name: Setup Gp
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-beta2
          stable: false

      - name: Build Client
        run: make client
        env:
          GO_BIN: go

      - name: Run Client
        run: ./tinyclient
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BASTION_API_ENDPOINT: ${{ secrets.BASTION_API_ENDPOINT }}
          OIDC_TOKEN: ${{ steps.oidc.outputs.token }}
